language: generic

sudo: required
services:
  - docker

before_Install:
  - docker build -t phrbshrp/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phrbshrp/test npm test

after_success:
  - docker build -t phrbshrp/multi-client ./client
  - docker build -t phrbshrp/multi-nginx ./nginx
  - docker build -t phrbshrp/multi-server ./server
  - docker build -t phrbshrp/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push phrbshrp/multi-client
  - docker push phrbshrp/multi-nginx
  - docker push phrbshrp/multi-server
  - docker push phrbshrp/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-474396719260"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
